import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';

interface BriefingData {
  communityName: string;
  company: string;
  date: string;
  acres: string;
  procedureNotes: string;
  spanishNotes: string;
  priorityAreas: string;
  priorityTasks: string;
  serviceMethod: string;
  logoBase64?: string; // We can pass a logo if we have one converted
}

export const generateBriefingPDF = (data: BriefingData) => {
  const doc = new jsPDF();

  // 1. Header & Branding
  doc.setFillColor(24, 24, 27); // Zinc-900
  doc.rect(0, 0, 210, 40, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(22);
  doc.text('TGS COMMERCIAL', 15, 20);
  
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text('FIELD OPERATIONS BRIEFING', 15, 28);
  
  doc.setFontSize(9);
  doc.text(`DATE: ${data.date}`, 160, 20);
  doc.text(`METHOD: ${data.serviceMethod.toUpperCase()}`, 160, 28);

  // 2. Body - Community Hero Section
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(28);
  doc.setFont('helvetica', 'bold');
  doc.text(data.communityName, 15, 60);
  
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 116, 139);
  doc.text(`${data.company} • ${data.acres} ACRES`, 15, 68);

  // 3. Structured Data Grid
  autoTable(doc, {
    startY: 80,
    margin: { left: 15, right: 15 },
    head: [['PRIORITY AREAS', 'PRIORITY TASKS']],
    body: [[data.priorityAreas || 'No specific areas flagged.', data.priorityTasks || 'No specific tasks flagged.']],
    theme: 'grid',
    headStyles: { fillColor: [241, 245, 249], textColor: [71, 85, 105], fontSize: 8, fontStyle: 'bold' },
    bodyStyles: { fontSize: 10, cellPadding: 8 }
  });

  // 4. Detailed Procedures (English)
  const finalY = (doc as any).lastAutoTable?.finalY || 80;
  
  doc.setFillColor(248, 250, 252);
  doc.rect(15, finalY + 10, 180, 40, 'F'); // Box for English
  
  doc.setFontSize(8);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(148, 163, 184);
  doc.text('PROCEDURE NOTES (ENGLISH)', 20, finalY + 18);
  
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(30, 41, 59);
  const englishLines = doc.splitTextToSize(data.procedureNotes || 'No procedure notes entered.', 170);
  doc.text(englishLines, 20, finalY + 26);

  // 5. Spanish Briefing (AI Optimized)
  const spanishStartY = finalY + 60;
  
  doc.setFillColor(239, 246, 255); // Light Blue for Spanish highlights
  doc.rect(15, spanishStartY, 180, 50, 'F');
  
  doc.setFontSize(8);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(59, 130, 246);
  doc.text('INSTRUCCIONES DE CAMPO (SPANISH)', 20, spanishStartY + 8);
  
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(30, 41, 59);
  const spanishLines = doc.splitTextToSize(data.spanishNotes || 'No translation available.', 170);
  doc.text(spanishLines, 20, spanishStartY + 16);

  // 6. Footer
  doc.setFontSize(8);
  doc.setTextColor(148, 163, 184);
  doc.text('Generated by TGS Commercial Intelligence System • Confidential Operations Document', 105, 285, { align: 'center' });

  // Save the PDF
  doc.save(`Briefing_${data.communityName.replace(/\s+/g, '_')}_${data.date}.pdf`);
};
